### ISSUE TITLE
out of the blue heimdall stops reporting non heimdall devices 

### ISSUE THREAD

**Issue by nattlip** [daneedk/com.uc.heimdall#21]
out of the blue heimdall stops reporting non heimdall devices in the settings log. only heimdall devices are reproted ie surveilans mode and alarm. rebooting homey or delting app and reinstalling dont help.

**Comment by daneedk** [comment]
Hello @nattlip, 

I can't reproduce the problem you have so it's a bit guessing what's going on.
Is this for just one device or others too? What happens if you select other devices for loggin only? What happens when you configure a device that is set to log to full or partial? Could it be you have an extensive log? Do you have enough free storage on your homey?

**Comment by nattlip** [comment]
problem is over
