### ISSUE TITLE
feature request: more movement info after the alarm went off

### ISSUE THREAD

**Issue by Tweaqer** [daneedk/com.uc.heimdall#25]
First off: amazing app! I installed it recently and it got tons of features. However when I installed it and linked it with Telegram I found that it sends a message only once after it activated the alarm on one of the sensors. My feature request would be to allow it to send other messages on other sensors too even though the alarm was already triggered so you'd know where a thief is moving. Love it even so :) 🥇 
Cheers!

**Comment by daneedk** [comment]
Thanks @Tweaqer 
The messages from monitored sensors when the alarm is activated are logged but will not lead to activating the **The alarm is activated** flow card by design. 
I will look into this, the first idea I get is to add a new trigger card something like **Tripped sensor while Alarm is active** (If that fits) with a _zone_ and _device_ tag.
With that card you can create a new flow to send a message through Telegram.

(btw, I appreciate leaving a review/rating in the appstore 👍 )

**Comment by Tweaqer** [comment]
Review was posted + donation made, thanks for the app and your consideration. Also the 'tripped sensor while alarm is active'-card would definitly solve it! Cheers

**Comment by daneedk** [comment]
Issue reopened to track progress

**Comment by daneedk** [comment]
Card is added, **Sensor tripped in Alarmstate** with the **Zone**, **Device** and **State** tags.

![image](https://user-images.githubusercontent.com/16610696/45771006-3fdc4b80-bc44-11e8-96f1-847ed1664144.png)

Available in version 1.0.20. (Will by submitted to the app store after testing)

**Comment by daneedk** [comment]
New version is published

**Comment by Tweaqer** [comment]
Today I had the chance to test it properly and it works great. Thanks @daneedk !
