### ISSUE TITLE
"Laatste Deur Functie" toevoegen (kort tijd in naar 10 seconden bij sluiten laatste deur)

### ISSUE THREAD

**Issue by Willybits** [daneedk/com.uc.heimdall#27]
In conventionele alarmsystemen is het gebruikelijk om de uitlooptijd te verkorten naar 10 seconden op het moment dat je de laatste deur van de uitgangsroute opent, en dan weer sluit. Op deze manier kun je een lange tijd instellen (aub langer dan 120 seconden.????) zodat je je niet hoeft te haasten. Dan wanneer de deur sluit zal na 10 seconden het alarm inschakelen.

De reden dat het alarm niet direct moet inschakelen, maar na 10 seconden na het sluiten van de laatste deur is omdat soms door een koude windvlaag door het openen van de deur, een bewegingsmelder in alarm kan gaan. Wat resulteert in alarm direct na inschakelen.

Deze optie is alleen beschikbaar op contacten, niet op bewegingsmelders.

**Comment by daneedk** [comment]
Heimdall can do a pre-arming check to inform you if any sensors are in a not desired state, but it’s up to the user to decided what to do with that information. 
The reason for this is that Homey has no uniform interface like an alarmsystem with an alarmpanel so I provided a flow triggercard that can be used to inform the user in his/hers desired method.

I made it this way (opening and closing during countdown to activate the Last Door functionality) because it seems more logical to me. Heimdall doesn’t block arming with open sensors, that’s up to the user.

**Comment by daneedk** [comment]
Splitting Trigger Delay into 2 separate settings, Arming Delay and Alarm Delay, is done.
Latest code is uploaded.

**Comment by Willybits** [comment]
Sounds cool! And indeed the approach is different with Homey vs conventional alarm systems, so that sounds logical too.

**Comment by daneedk** [comment]
Last Door functionality is in version 1.0.22 which I just submitted for approval.

**Comment by daneedk** [comment]
Version 1.0.22 is approved and published.
https://community.athom.com/t/topic/134/26
