### ISSUE TITLE
Heimdall does not work on Homey 2.0

### ISSUE THREAD

**Issue by daneedk** [daneedk/com.uc.heimdall#31]
This is known. With the release of Homey 2.0 the athom-api which Heimdall relies on is also updated to a new version. Heimdall needs to be rewritten to function with the new athom-api.

**Comment by satbopper** [comment]
i will not put you under pressure but i will tell you what happened,on 1.5.13 i worked with heimdall,no problems,made flows what to do when an alarm occured,so i have a motion detector in the garage (full)
in the settings.all that worked great in 1.5.13
i installed homey v2 so heimdall is not working as known,but that is not 100 % true because for a particular reason i moved the garage detector from the garage into the house
Last night this occured when you do not disable the app heimdall and certain flows my alarm under v2 went on during the night,and here it is a large sirene
so for some reason parts of the heiimdall app is working in v2

**Comment by daneedk** [comment]
Sorry for waking you up last night ;) but in a way it seems like good news. From that it looks like the listening to sensors still work. I know the listing of devices in the settings don't work so that would be my first priority and of course making a usable view on a phone.

The [donations](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134/82?u=daneedekruyff) are reaching 80% so I'm almost able to get another Homey for development so I can rewrite Heimdall for V2

**Comment by daneedk** [comment]
Development of the rewrite is ongoing, the result can be found in the [alpha-V2](https://github.com/daneedk/com.uc.heimdall/tree/alpha-V2) branche.

**Comment by daneedk** [comment]
Heimdall 2.0.0 is compatible with Homey 2.0 and is available in the [App Store](https://apps.athom.com/app/com.uc.heimdall)
