### ISSUE TITLE
devices error

### ISSUE THREAD

**Issue by satbopper** [daneedk/com.uc.heimdall#39]
the devices error session expired is now also on heimdall and the groups app
i mailed weejewel for this annoying issue

**Comment by daneedk** [comment]
Hi Satbopper, 

Thanks informing me, I’m not aware of the issue you’re mentioning but also saw your message on Slack. Could you point me to more information about this to see what it is and how it affects Heimdall?

Thanks!

**Comment by satbopper** [comment]
it will give give a popup screen,if you go to apps and then heimdall and then config you will get a popup screen with getdevices error,er is een onbekende fout opgetreden [session expired]
if you go to apparaten the popup screen will go on and off,heimdall is not functioning anymore
i read but i am not sure that this will be solved according weejewel in the next release of homey

**Comment by satbopper** [comment]
with the workaround from weejewel it works again

**Comment by daneedk** [comment]
Thanks for the additional information!

The issue has been acknowledged by Athom and will be fixed in the next Homey version. At this time it is unknown when this version will be released.

For others to see if they are bitten by the same bug, please go to the ***Heimdall*** settings.
![image](https://user-images.githubusercontent.com/16610696/56430764-af441780-62c7-11e9-84b7-58d335e032e7.png)

When this error is shown please take the steps below to get ***Heimdall*** (and any other app using the Athom WEB-API) working again.
If others run into the same issue, please take the following steps:

From a PC, open Chrome and start an Incognito window:
```
Windows, Linux or Chrome OS: Press Ctrl + Shift + n.
Mac: Press ⌘ + Shift + n.
```
Navigate to the [Homey Developer](https://developer.athom.com) site and logon.
Now go to the [Web API Playground](https://developer.athom.com/tools/api-playground)
replace the `Homey.users.getUserMe();` with this command:
```
Homey.sessions.getSessions().then(s => Promise.all(Object.values(s).filter(s => s.type === 'APP' && new Date(s.expiresAt).getTime() < Date.now()).map(s => Homey.sessions.deleteSession({id: s.id}))))
```
So it will look like this
![image](https://user-images.githubusercontent.com/16610696/56430458-b3236a00-62c6-11e9-8dee-9023804e3aa4.png)
Click the `RUN` button to activate the command.

The next step will be to restart the ***Heimdall*** app, to do this open the Homey app on your Phone and go to `More` and select `Apps`

Select the ***Heimdall*** app and press the cogwheel in the upper right corner.
Next click on `Restart app`

After this last step ***Heimdall*** should be functioning as expected.

**Comment by ptahbe** [comment]
@daneedk Thx. Now it's working again.

**Comment by daneedk** [comment]
Bug has been fixed by Athom.
