### ISSUE TITLE
Heimdall Issues

### ISSUE THREAD

**Issue by catowk** [daneedk/com.uc.heimdall#47]
I have some issue regarding the heimdall app.
When the heimdall is in Armed mode and the trigger goes of and i will put the Mode back in Disarmed mode it start writing disarmed to the timline in homey and also heimdall app every second.  I have to reset homey to make this stop.

**Comment by daneedk** [comment]
Hello Catowk,

Can you tell me how you set the **Surveillance Mode** to **Disarmed**? Do you use the **Surveillance Mode Switch** or do you use a flow?

Another user reported something that looks like this earlier on the forum (https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134/670) but I was unable to reproduce. For him the problem was resolved while nothing changed in the app and it looked like somehow Homey itself caused the (in his case) double Disarming which resulted in the double reports in the timeline.

**Comment by catowk** [comment]
Hi daneedk,
And thank you for quick answer. I set the Surveillance Mode with the app connect life360 when the phone is home. see the link.(Flow)

![Flow disarmed](https://user-images.githubusercontent.com/60130549/72840716-1c406f80-3c95-11ea-9047-8d5c1f6c53db.JPG)

I have tried to uinstall the heimdall and install it again this evening. And see wat happening.

I will look at the link you sent me.
