### ISSUE TITLE
Countdown issue

### ISSUE THREAD

**Issue by dirkg173** [daneedk/com.uc.heimdall#49]
When I activate the "Partially secured" mode in the evening, Homey starts to count down. I have set a delay of 120 seconds to give me enough time to close windows. The problem is that Homey counts backwards from 120, when it reaches 100 seconds it skips 90 seconds and the countdown continues with 10 seconds (120, 115, 110, 105, 100, 10, 9, 8, 7,....).

**Comment by daneedk** [comment]
I can't reproduce the issue, for me it does a nice countdown from 120 down to 10 every 5 seconds and each second after that. 

- Does the led ring turn yellow every 5 seconds?
- What language is configured in your Homey? (I've used English)
- Can you make a flow like below, does it leave a message every seconds in your Timeline?
![image](https://user-images.githubusercontent.com/16610696/82751438-8c800e80-9db7-11ea-8001-754001ba6342.png)

**Comment by dirkg173** [comment]
Many thanks for the response!
- Does the led ring turn yellow every 5 seconds? -> Yes
- What language is configured in your Homey? German
- Does it leave a message every seconds in your Timeline? No, there's an interruption.
However, last night the time between 100 and 10 seconds was not interrupted, but after 45 seconds (see Timeline, I didn't delete any entries).
I sent you a diagnostic report this morning: 6c1a07b7-0000-4ff4-a045-1968f335cebf

![DB71523A-C501-4F8B-99BF-3F9C3CE28436](https://user-images.githubusercontent.com/40319629/82797140-f01d4100-9e76-11ea-8067-0fd2d8580ae3.png)

**Comment by daneedk** [comment]
Thanks for your answers.
- The fact the led ring turns yellow every 5 seconds tells me the speech command is send from Heimdall (hence the light ring lighting up)
- You could try setting it to English to see if it's a problem specific for German.
- The interruption is caused by Homeys Rate limiting kicking in (Expected, an app is not allowed to send that many information to the Timeline) but it proves me the code that is used to fire the speech is executed because it's in the same function as triggering the flow card.

Unfortunately the fact that the text isn't spoken is beyond my control so you will have to take it up with Athom.
Relevant code (if they want to look into what Heimdall does):
https://github.com/daneedk/com.uc.heimdall/blob/7f23416996c1429d2a55320990be63f6054ccfca/app.js#L999-L1003

https://github.com/daneedk/com.uc.heimdall/blob/7f23416996c1429d2a55320990be63f6054ccfca/app.js#L909-L912

**Comment by dirkg173** [comment]
Thank you very much for the answer!

Tonight I will try to set the language to English and give you some feedback.

Last night the countdown already jumped from 108 to 10 seconds.
While the countdown is running I still open and close windows with sensors, which are also activated for the partial mode in Heimdall. Could it possibly be caused by this?

Unfortunately I do not understand the code, I have only little IT knowledge.

![82A29CBB-78EC-4154-AE03-F5AA4E9EDFD8](https://user-images.githubusercontent.com/40319629/82865410-f4089c00-9f26-11ea-9357-166e8ac7843d.png)

**Comment by daneedk** [comment]
> Last night the countdown already jumped from 108 to 10 seconds.
While the countdown is running I still open and close windows with sensors, which are also activated for the partial mode in Heimdall. Could it possibly be caused by this?

No, it can't.

**Comment by dirkg173** [comment]
Last night the countdown jumped to 10 seconds again after a short time, although the setting was English.
There is also no other flow that might activate the surveillance mode a second time, or something similar.
I added screenshots of the relevant flows and sent another diagnostic report: b9f193f8-8117-40b4-84ad-356e6d1b83f4

![D7041B0B-0C93-4BC9-874F-FDB46E43C94E_1_101_o](https://user-images.githubusercontent.com/40319629/82987130-56c96880-9ff7-11ea-8eb4-f22970158b69.jpeg)

<img width="278" alt="Bildschirmfoto 2020-05-27 um 08 45 49" src="https://user-images.githubusercontent.com/40319629/82987157-621c9400-9ff7-11ea-97f5-5bcb672dc38c.png">
<img width="269" alt="Bildschirmfoto 2020-05-27 um 08 46 16" src="https://user-images.githubusercontent.com/40319629/82987158-634dc100-9ff7-11ea-8880-b083249a08be.png">
<img width="276" alt="Bildschirmfoto 2020-05-27 um 08 46 33" src="https://user-images.githubusercontent.com/40319629/82987159-634dc100-9ff7-11ea-81a9-65b7fdb1c3d0.png">

**Comment by daneedk** [comment]
Ah, now I see what's happening. You've activated the **[Last Door Functionality](https://community.athom.com/t/heimdall-let-homey-watch-over-your-home/134#heading--lastdoor)**

When you set a (**Partially**) **Armed Surveillance Mode** with a **Arming Delay** and open and close a contact sensor (so a door or window) that has a **Delay** the countdown timer is brought down to 10 seconds. 
This is by design, you can check this on ***Heimdalls*** **Dashboard** on the settings pages:
![image](https://user-images.githubusercontent.com/16610696/82989295-bc6b2400-9ffa-11ea-9368-ea1bb2b44614.png)

**Comment by dirkg173** [comment]
Okay, got it.
I will remove the "delay" on all sensors because I don't need the "Last Door Functionality". That should solve the problem.

I'm sorry for the trouble. The problem was not the Heimdall app, the problem was in front of the computer.

Thanks for your support!

**Comment by daneedk** [comment]
You're welcome, Glad we found out what was going on!
