### ISSUE TITLE
Vibration Sensor not shown in Heimdall 

### ISSUE THREAD

**Issue by clipse2004** [daneedk/com.uc.heimdall#55]
Hello,
First of all great work! 
I have a problem though and that is all my Aqara vibration and contact sensors are running via Deconz and App in the Homey.
There I see all the sensors, but when I look in the Heimdall app, I see only the contact sensors. The vibration sensors are missing completely :/ 
Do you have a tip for me? 

Merci

**Comment by daneedk** [comment]
Hello,

That's unfortunately caused by the fact that in the Deconz app the capability used for vibration is created by its developer without looking at what was already used for vibration (_alarm_vibration_) by the Aqara & Xiaomi App and ignoring the naming scheme Athom used for capabilities

There's 2 ways to solve this, the first is to move the sensor to Homey* and use the Aqara & Xiaomi app (https://homey.app/nl-nl/app/com.xiaomi-mi/Aqara-&amp;-Xiaomi-ZigBee/) 
The second would be to create a virtual device where you set a capability based on the state from your actual sensor.
How to use a Virtual Device is explained here: https://community.athom.com/t/topic/134/8 

\* If you're not on Homey firmware 5.0 I'd suggest you to wait until 5.0 reaches stable.
