### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by perpatrik79** [daneedk/com.uc.heimdall#56]
I have had problems with Heimdal the last couple of weeks. When I try to arm or disarm, Homey crashes and has to be restarted with a hard reset. I have now inactivated the Heimdal app and Homey seems to be working fine. The problem became evident when I updated the Homey firmware to 7.1.1.

**Comment by daneedk** [comment]
All apps in Homey are sandbox and should not be able to crash Homey. I have received 3 reports from Homeys on 7.1.1 a week ago, so I suspect these to be from you. These reports indicate the app ran into a problem, most likely because of depleted resources but as far as I can see these did not cause the app to crash. 
I can't easily troubleshoot what's going on, I advise you to look at the memory and cpu usage of your Homey.

(To put this in perspective; In total I've received 7 reports over the last year on over 5000 installs)

**Comment by perpatrik79** [comment]
Thank you for your reply. You are probobly right that all three reports
came from me; I had trouble sending the report and therefore tried several
times.

I have since tried to delete the app and then reinstall it. So far it seems
to be working.

Thank you for a very useful app.

Sincerely,
Patrik Bergman

tis 17 aug. 2021 kl. 19:40 skrev Danee ***@***.***>:
