### ISSUE TITLE
Undefined triggers alarm

### ISSUE THREAD

**Issue by markussandin1** [daneedk/com.uc.heimdall#58]
When surveillance mode is active, the alarm goes of because of “undefined in undefined triggered Alarm”. 
I can’t understand what’s going on, all my devices works and shows up in Heimdall Homey app. In the log I see that “Flowcard” is the same time as “undefined” in the Homey status log. 
![43010753-D3DF-4D0E-B901-C6A613D5BF46](https://user-images.githubusercontent.com/19946298/140402548-1a984215-6fab-4a0c-af0e-c356d5ea92f5.png)
![698085E0-BA4D-402B-A1F9-04EF2967E3B6](https://user-images.githubusercontent.com/19946298/140403013-e109dbc8-ae96-4ecc-8423-2ecdae62813b.jpeg)

**Comment by daneedk** [comment]
Hi Markus,

Heimdall responds on information send to it by Homey, how this can be undefined is not clear to me as I've never seen this before.
Can you please stop and restart Heimdall and send me a diagnostics report after a few minutes? That way I can see which devices are reported by Homey and how they are reported.
Next, reproduce the issue, if possible otherwise you'll have to wait till it happens again, and again send a diagnostics report. Please mention your name and the bug id (58) in the reports so I know you sent them.

Thanks,

Danee

**Comment by markussandin1** [comment]
Hi,

I think I've figured out the problem. 
I had a flow to trigger the alarm, what I should have is a flow that triggers Surveillance mode. So a misunderstanding from me how it works. 
So "undefined" is when the alarm is triggered by a flow. ![image](https://user-images.githubusercontent.com/19946298/140621696-3cd8057d-2fab-45fd-a7f5-8ffbe1e9d039.jpeg)
