### ISSUE TITLE
Aqara vibration sensor

### ISSUE THREAD

**Issue by eeckelaertyannick** [daneedk/com.uc.heimdall#60]
Hi Danee,

I have a aqara vibration sensor. This sensor can detect vibration, tilt en drop sensor. In Heimdall it only displays the vibration sensor not the other 2 can you make it that is can use the other 2?

Would be great!

**Comment by daneedk** [comment]
Hi, 
It's by design only vibration is used. When implementing support I wasn't able to trigger any of the other sensors *without* also triggering the vibration so I decided to only include that capability as it would cover all sensors. Also, it would require a massive rewrite of the app to include for example the tilt sensor as that would undoubtedly lead to questions about setting the angle. 

Cheers,

Danee
