### ISSUE TITLE
SDK3 Ring keypad don't work

### ISSUE THREAD

**Issue by bakker284** [daneedk/com.uc.heimdall#64]
Ring keypad don't work after entering pin , changing heimdall surveillance in app does work on keypad ( heimdall will change ring keypad state)

**Comment by daneedk** [comment]
Thanks for reporting!

I now realize that testing the Ring integration isn’t possible when running of of the apps from the CLI. The Ring app has an API key that can not be checked when Heimdall is running from the CLI. The fact that the Ring Keypad does show the correct is because Heimdall sends out events that the Ring app listens too so that part is tested.

If have tested arming, partially arming and disarming from both a Ring Keypad v1 and v2 so that part doesn’t really need additional testing.

If you do want to test it, just because you can, you will have to run both apps from the cli and place an env.json file in the apps folders. Please let me know if you want to and I will create the needed files for you

**Comment by bakker284** [comment]
its up to you if you think its not necessary then we leave like this

**Comment by daneedk** [comment]
I think it will be ok, let's leave this part like this.
